### ISSUE TITLE
Her har dere stavet yatzy feil!

### ISSUE THREAD

**Issue by jhannes** [Westerdals/pgr203-assignment-1-amish1188#4]
### https://github.com/Westerdals/pgr203-assignment-1-amish1188/blob/3422ba6c49ec9a0c7bb6a643d88acb9afaef8d2e/src/test/java/no/kristiania/yatzy/yatzyGame.java#L6

**Comment by amish1188** [comment]
jeg har egentlig sjekket på wikipedia og det skrives yatzy :P. Tror ikke det spiller en rolle. Har bare byttet navnet på en av klassene så at begge to har "yatzy" i navnet
